# Assignment 1: NumPy Part 1


## Learning Objectives
This lesson meets the following learning objectives:

- The ability to use Python data structures provided in NumPy.

## Instructions
Read through all of the text in this page. This assignment provides step-by-step training divided into numbered sections. The sections often contain embeded exectable code for demonstration.  Section headers with icons have special meanings:  

- <i class="fas fa-puzzle-piece"></i> The puzzle icon indicates that the section provides a practice exercise that must be completed.  Follow the instructions for the exercise and do what it asks.  Exercises must be turned in for credit.
- <i class="fa fa-cogs"></i> The cogs icon indicates that the section provides a task to perform.  Follow the instructions to complete the task.  Tasks are not turned in for credit but must be completed to continue progress.

Review the list of items in the **Expected Outcomes** section to check that you feel comfortable with the material you just learned. If you do not, then take some time to re-review that material again. If after re-review you are not comfortable, do not feel confident or do not understand the material, please ask questions on Slack to help.

Follow the instructions in the **What to turn in** section to turn in the exercises of the assginment for course credit.

## Background
This notebook is based on the official `NumPy` [documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html).  Unless otherwise credited, quoted text comes from this document.  The Numpy documention describes NumPy in the following way:

> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> - a powerful N-dimensional array object
> - sophisticated (broadcasting) functions
> - tools for integrating C/C++ and Fortran code
> - useful linear algebra, Fourier transform, and random number capabilities
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


## <i class="fa fa-cogs"></i> Notebook Setup
First, we must import the NumPy library.  All packages are imported at the top of the notebook. Execute the code in the following cell to get started with this notebook (type Ctrl+Enter in the cell below)

In [ ]:
# Import numpy
import numpy as np

The code above imports numpy as a variable named `np`. We can use this variables to access the functionality of NumPy.  The above is what we will use for the rest of this class.

You may be wondering why we didn't import numpy like this:  
```python
import numpy
```
We could, but the first is far more commonly seen, and allows us to the `np` variable to access the functions and variables of the NumPy package. This makes the code more readable because it is not a mystery where the functions come from that we are using.

## 1. The NumPy Array
### 1.1. Learning
What is an array?  An array is a data structure that stores one or more objects of the same type (e.g. integers, strings, etc.) and can be multi-dimensional (e.g. 2D matricies). In python, the list data type provides this type of functionality, however, it lacks important operations that make it useful for scientific computing.  Therefore, NumPy is a Python package that defines N-dimensional arrays and provides support for linear algebra, and other fucntions useful to scientific computing.

From the Numpy QuickStart Tutorial: 
> NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. 

<div class="alert alert-warning">
    <b>Note</b>:  a "tuple" is a list of numbers. For example, the pair of numbers surrounded by parentheses: (2,4), is a tuple containing two numbers.
</div>

NumPy arrays can be visualized in the following way:

<img src="./media/A01-content_arrays-axes.png">

(image source: https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

Using built-in Python lists, arrays are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = [1,2,3]  

# A 2-dimensional list of numbers.
my_2d_array = [[1,2,3],[4,5,6]]

# A 3-dimensional list of numbers.
my_3d_array = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]

# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

```

Using NumPy, arrays are created using the `np.array()` function. For example, arrays with the same contents as above are created in the following way:

```python
# A 1-dimensional list of numbers.
my_array = np.array([1,2,3,4])

# A 2-dimensional list of numbers.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])

# A 3-dimensional list of numbers.
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])

# Two lists of boolean values
a = np.array([True,True,False,False])
b = np.array([False,False,True,True])
```

In NumPy, these arrays are an object of type `ndarray`.  You can learn more about the `ndarray` class on the [NumPy ndarray introduction page](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html). However, this tutorial will walk you through some of the most important attributes, functions and uses of NumPy.

### 1.2. <i class="fas fa-puzzle-piece"></i> Practice

Perform the following in the cell below.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [11]:
my_array = np.array([1,3,5,8])
print(my_array, '\n')
my_2darray = np.array([[1,3,5,8], [2,4,6,8]])
print(my_2darray, '\n')
my_3darray = np.array([[[1,3,5,8], [2,4,6,8]], [[1,3,5,7], [9,11,13,17]]])
print(my_3darray, '\n')

[1 3 5 8] 

[[1 3 5 8]
 [2 4 6 8]] 

[[[ 1  3  5  8]
  [ 2  4  6  8]]

 [[ 1  3  5  7]
  [ 9 11 13 17]]] 



## 2. Array Attributes
### 2.1. Learning 
For this section we will retrieve information about the arrays. Once an array is created you can access information about the array such as the number of dimensions, its shape, its size, the data type that it stores, and the number of bytes it is consuming. There are a variety of attributes you can use such as:
+ `ndim`
+ `shape`
+ `size`
+ `dtype`
+ `itemsize`
+ `data`
+ `nbytes`

For example, to get the number of dimensions for an array:
```Python
# Print the number of dimensions for the array:
print(my_3d_array.ndim)
```

You can learn more about these attributes, and others from the [NumPy ndarray reference page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) if you need help understanding the attributes.

Notice that we use dot notation to access these attributes, yet we do not provide the parenthesis `()` like we would for a function call.  This is because we are accessing attributes (i.e. member variables) of the numpy object, we are not calling a function

### 2.1. <i class="fas fa-puzzle-piece"></i> Practice



In the cell below, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [10]:
my_3darray = np.array([[[1,3,5,8], [2,4,6,8]], [[1,3,5,7], [9,11,13,17]]])
#prints the number of dimensions in the array
print(my_3darray.ndim)
#prints the shape of the array
print(my_3darray.shape)
#prints the size of the array
print(my_3darray.size)
#prints the data type of the array
print(my_3darray.dtype)
#prints one array element size in bytes.
print(my_3darray.itemsize)
#prints the object that leads to the start of the data
print(my_3darray.data)
#prints the total bytes consumed by the array
print(my_3darray.nbytes)

3
(2, 2, 4)
16
int32
4
64


## 3. Creating Initialized Arrays
### 3.1. Learning

Here we will learn to create initialized arrays. These arrays are pre-initalized with default values.  NumPy provides a variety of functions for creating and intializing an array in easy-to-use functions. Some of these include: 

+ [np.ones()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones): Returns a new array of given shape and type, filled with ones.
+ [np.zeroes()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros): Returns a new array of given shape and type, filled with zeros.
+ [np.empty()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty): Return a new array of given shape and type, without initializing entries.
+ [np.full()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full): Returns a new array of given shape and type, filled with a given fill value.
+ [np.arange()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html#numpy.arange): Returns a new array of evenly spaced values within a given interval.
+ [np.linspace()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html#numpy.linspace): Returns a new array of evenly spaced numbers over a specified interval.
+ [np.random.random](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.random.html): Can be used to return a single random value or an array of random values between 0 and 1.

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output (i.e array) it generates.

NumPy has a large list of array creation functions, you can learn more about these functions on the [array creation routins page](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html) of the NumPy documentation. 

To demonstrate the use of these functions, the following code will create a two-dimensional array with 3 rows and 4 columns (i.e 3 *x* 4) filled with 0's.  

```Python
zeros = np.zeros((3, 4))
```

The following creates a 1D array of values between 3 and 7

```Python
np.arange(3, 7)
```
The result is: `array([3, 4, 5, 6])`

The following creates a 1D array of values between 0 and 10 spaced every 2 integers:

```Python
np.arange(0, 10, 2)
```
The result is: `array([0, 2, 4, 6, 8])`

Notice that just like with Python list slicing, the range uncludes up-to, but not including the "stop" value of the range.


### 3.1. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [15]:
# Import numpy
import numpy as np
#Creates a 3x2 array filled with ones and prints it
a_1 = np.ones([3, 2])
print('ones')
print(a_1)
#Creates a 3x3 array filled with zeros and prints it
b_1 = np.zeros([3, 3])
print('zeros')
print(b_1)
#Creates a 4x4 array that is empty and prints it (but its empty so it doesn't)
c_1 = np.empty([4, 4])
print('empty')
print(c_1)
#Creates a 3x6 array filled with the int 6
d_1 = np.full([3, 6], 6)
print('full')
print(d_1)
#Creates an array of the numbers from 0 to 100 by tens
e_1 = np.arange(0, 100, 10)
print('arrange')
print(e_1)
#Creates an array of evenly numbers evenly spaced from 0 - 100
f_1 = np.linspace(0, 100)
print('linspace')
print(f_1)
#Creates an 3x6 array of random numbers between 0-1
g_1 = np.random.random([3, 6])
print('random')
print(g_1)

ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]
zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
empty
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.24611266e-306]
 [7.56587584e-307 1.37961302e-306 1.05699242e-307 8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306]
 [2.22522597e-306 6.23053614e-307 1.60221072e-306 1.42410974e-306]]
full
[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]
arrange
[ 0 10 20 30 40 50 60 70 80 90]
linspace
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346

## 4. Performing Math and Broadcasting
### 4.1. Learning

At times you may want to apply mathematical operations between arrays. For example, suppose you wanted to add, multiply or divide the contents of two arrays.  If the two arrays are the same size this is straightfoward. However if the arrays are not the same size then it is more challenging.  This is where Broadcasting comes to play:

> The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. (https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)


#### 4.1.1. Arrays of the same size
To demonstrate math with arrays of the same size, the following cell contains code that creates two arrays of the exact same size: _3 x 4_.  Execute the cell to create those arrays:

In [16]:
# Define demo arrays:
demo_a = np.ones((3,4))
demo_b = np.random.random((3,4))

# Print the shapes of each array.
print(f"demo_a shape: {demo_a.shape}")
print(f"demo_b Shape: {demo_b.shape}")

demo_a shape: (3, 4)
demo_b Shape: (3, 4)


Let's print the array to see what they contain:

In [17]:
print(demo_a)
print(demo_b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.86076003 0.88662315 0.66638616 0.17948703]
 [0.93975843 0.10638024 0.21773896 0.86666784]
 [0.96615126 0.24418266 0.45625231 0.9602467 ]]


Because these arrays are the same size we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [18]:
# These arrays have the same shape, 
demo_a + demo_b

array([[1.86076003, 1.88662315, 1.66638616, 1.17948703],
       [1.93975843, 1.10638024, 1.21773896, 1.86666784],
       [1.96615126, 1.24418266, 1.45625231, 1.9602467 ]])

The addition resulted in the corresponding positions in each matrix being added to the other and creating a new matrix.  If you need clarification for how two matricies can be added or subtracted see the [Purple Math](https://www.purplemath.com/modules/mtrxadd.htm) site for examples.

#### 4.1.2. Broadcasting for Arrays of Different Sizes
When arrays are not the same size, you cannot perform simple math.  For this, NumPy provides a service known as "broadcasting". To broadcast, NumPy automatically resizes the arrays to match, and fills in newly created empty cells with values.

To Broadcast, NumPy begins at the right-most dimensions of the array and comparses them then moves left and compares the next set. As long as each set meet the following criteria, Broadcasting can be performed:

+  The dimensions are equal or
+  One of the dimensions is 1.

Consider two arrays of the following dimensions:

+ 4D array 1:  10 x 1 x 3 x 1
+ 3D array 2:       2 x 1 x 9

These arrays are not the same size, but they are compatible with broadcasting because at each diemsion (from right to left) the dimension crtieria is met. When performing math, the value in each dimension of size 1 is broadcast to fill that dimesion (an example is provided below). The resulting array, if the above arrays are added, will be broadcasted to a size of _10 x 2 x 3 x 9_

To demonstrate math with arrays of different size, the following cell contains code that creates two arrays: one of size _3 x 4_ and onther of size _4 x 1_.  Execute the cell to create those arrays:

In [19]:
# Create the arrays.
demo_c = np.ones((3,4))
demo_d = np.arange(4)

# Print the array shapes.
print(f"demo_c shape: {demo_c.shape}")
print(f"demo_d Shape: {demo_d.shape}")

demo_c shape: (3, 4)
demo_d Shape: (4,)


Let's print the array to see what they contain:

In [20]:
print(demo_c)
print(demo_d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


Because these arrays meet our brodcasting requirements, we can perform basic math by using common arithamtic symbols. Exectue the following cell to see the results of adding the two demo arrays:

In [21]:
demo_c + demo_d

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

The addition resulted in the value in each dimension of size 1, being "broadcast" or "streched" throughout that dimesion and then used in the operation. 

#### 4.1.3. Broadcasting With Higher Dimensions

Consider the following arrays of 2 and 3 dimensions. 

In [26]:
demo_e = np.ones((3, 4))
demo_f = np.random.random((5, 1, 4))
print(f"demo_e shape: {demo_e.shape}")
print(f"demo_f shape: {demo_f.shape}")

demo_e shape: (3, 4)
demo_f shape: (5, 1, 4)


Print the arrays to see what they contain:

In [27]:
print(demo_e)
print(demo_f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.47319084 0.52051698 0.67311525 0.61125095]]

 [[0.52025625 0.9351756  0.61169771 0.65407188]]

 [[0.4933753  0.74470811 0.09644875 0.53025316]]

 [[0.52148962 0.04655127 0.1625175  0.01878594]]

 [[0.87965384 0.38630836 0.52278936 0.97038774]]]


These two arrays meet the rules for broadcasting becuase they both have a 4 in their last dimension and there is a 1 in the  `demo_f` 2nd dimension.  

Perform the math by executing the following cell:

In [28]:
result = demo_e + demo_f
print(result)

[[[1.47319084 1.52051698 1.67311525 1.61125095]
  [1.47319084 1.52051698 1.67311525 1.61125095]
  [1.47319084 1.52051698 1.67311525 1.61125095]]

 [[1.52025625 1.9351756  1.61169771 1.65407188]
  [1.52025625 1.9351756  1.61169771 1.65407188]
  [1.52025625 1.9351756  1.61169771 1.65407188]]

 [[1.4933753  1.74470811 1.09644875 1.53025316]
  [1.4933753  1.74470811 1.09644875 1.53025316]
  [1.4933753  1.74470811 1.09644875 1.53025316]]

 [[1.52148962 1.04655127 1.1625175  1.01878594]
  [1.52148962 1.04655127 1.1625175  1.01878594]
  [1.52148962 1.04655127 1.1625175  1.01878594]]

 [[1.87965384 1.38630836 1.52278936 1.97038774]
  [1.87965384 1.38630836 1.52278936 1.97038774]
  [1.87965384 1.38630836 1.52278936 1.97038774]]]


The resulting array has dimensions of _5 x 3 x 4_.  For this math to work, the values from `demo_f` had to be "stretched" (i.e. copied and then added) in the second dimension

### 4.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [35]:
prac_1 = np.random.random((4, 3))
prac_2 = np.random.random((3, 1, 3))
print(f"prac_1 shape: {prac_1.shape}")
print(f"prac_2 shape: {prac_2.shape}")

print(prac_1)
print(prac_2)

print('Addition')
result_1 = prac_1 + prac_2
print(result_1)
print('Subtraction')
result_2 = prac_2 - prac_1
print(result_2)
print('Multiplication')
result_3 = prac_1 * prac_2
print(result_3)

prac_1 shape: (4, 3)
prac_2 shape: (3, 1, 3)
[[0.77244064 0.90815635 0.76832872]
 [0.07895085 0.50048466 0.45239587]
 [0.87320835 0.5867262  0.9759513 ]
 [0.43946075 0.86816632 0.27685583]]
[[[0.03217209 0.98493463 0.91604916]]

 [[0.97539686 0.69086483 0.78544064]]

 [[0.76811809 0.38541149 0.63921985]]]
Addition
[[[0.80461273 1.89309098 1.68437788]
  [0.11112294 1.48541929 1.36844503]
  [0.90538044 1.57166083 1.89200046]
  [0.47163283 1.85310095 1.192905  ]]

 [[1.7478375  1.59902118 1.55376936]
  [1.05434771 1.19134949 1.23783651]
  [1.84860521 1.27759103 1.76139194]
  [1.41485761 1.55903115 1.06229648]]

 [[1.54055874 1.29356783 1.40754857]
  [0.84706895 0.88589614 1.09161572]
  [1.64132645 0.97213769 1.61517115]
  [1.20757884 1.25357781 0.91607568]]]
Subtraction
[[[-0.74026856  0.07677828  0.14772044]
  [-0.04677877  0.48444997  0.46365329]
  [-0.84103627  0.39820843 -0.05990214]
  [-0.40728866  0.11676831  0.63919333]]

 [[ 0.20295621 -0.21729152  0.01711193]
  [ 0.896446    0.19

## 5. NumPy Aggregate Functions
### 5.1. Learning

NumPy also provides a variety of functions that "aggregate" data. Examples of aggreagation of data include calculating the sum of every element in the array, calculating the mean, standard deviation, etc.  Below are a few examples of aggregation functions provided by NumPy.

#### 5.1.1 Mathematical Functions
+ [np.sum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html): sums the array elements over a given axis
+ [np.minimum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html#numpy.minimum): compares two arrays and returns a new array of the minimum at each position (i.e. element-wise)
+ [np.maximum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html#numpy.maximum): compares two arrays and returns a new array of the maximum at each position (i.e. element-wise).
+ [np.cumsum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html#numpy.cumsum): returns the cummulative sum of the elements along a given axes.

You can find more about mathematical functions for arrays at the [Numpy mathematical functions page](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

#### 5.1.2 Statistics
+ [np.mean()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html): compute the arithmetic mean along the specified axis.
 [np.median()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html#numpy.median): compute the median along the specified axis.
+ [np.corrcoef()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy.corrcoef): return Pearson product-moment correlation coefficients between two 1D arrays or one 2D array.
+ [np.std()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html#numpy.std): compute the standard deviation along the specified axis.
+ [np.var()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html#numpy.var): compute the variance along the specified axis.

You can find more about statistical functions for arrays at the [Numpy statistical functions page](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html).


Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

For example:
```Python
# Calculate the sum of our demo data from above
np.sum(demo_e)
```


In [38]:
# Calculate the mean of our demo data from above
np.mean(demo_f)

0.5186272194692145

#### 5.1.3 Logical Aggregate Functions
When arrays contain boolean values there are additional logical aggregation functions you can use: 

 + [logical_and()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html#numpy.logical_and): computes the element-wise truth value of two arrays using AND.
 + [logical_or()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_or.html#numpy.logical_or): computes the element-wise truth value of two arrays using OR.
 + [logical_not()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html#numpy.logical_not):  computes the element-wise truth value of two arrays using NOT.
 
 
You can find more about logical functions for arrays at the [Numpy Logic functions page](https://docs.scipy.org/doc/numpy/reference/routines.logic.html).

Take a moment, to learn more about the functions listed above by clicking on the function name as it links to the NumPy documentation.  Pay attention to the arguments that each receives and the type of output it generates.

To demonstrate usage of the logical functions, please execute the following cells and examine the results produced.

### 5.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  

In [54]:
# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

# Creates a 3x3 array filled with 1s
a_1 = np.ones([3, 3])
print('ones')
print(a_1)

# Creates a 3x3 array filled with zeros and prints it
b_1 = np.zeros([3, 3])
print('zeros')
print(b_1)

# Creates a 3x6 array filled with random 0-1
d_1 = np.random.random([3, 6])
print('Random')
print(d_1)

d_1_2 = np.random.random([3, 6])
print('Random')
print(d_1_2)

# Creates an array of the numbers from 0 to 100 by tens
e_1 = np.arange(0, 100, 10)
print('arrange')
print(e_1)

# Perform a logical "or":
print('Logic')
print(np.logical_or(a, b))

# Perform a sumation of the array
print('Sumation')
print(np.sum(e_1))

# find the minimum value between two arrays
print('minimum')
print(np.minimum(d_1, d_1_2))

# find the minimum value between two arrays
print('maximum')
print(np.maximum(d_1, d_1_2))

# find the minimum value between two arrays
print('cumsum')
print(np.cumsum(e_1))

# find the mean value of an array
print('Mean')
print(np.mean(e_1))

# find the Correlation coefficient for an array
print('Correlation')
print(np.corrcoef(d_1))

# find the standard deviation of an array
print('Std')
print(np.std(e_1))

# find the variance of an array
print('Var')
print(np.var(e_1))

ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Random
[[0.4501989  0.89861108 0.64110013 0.46218705 0.74208781 0.46027288]
 [0.26662042 0.91817351 0.42469097 0.52986336 0.82111741 0.46117473]
 [0.18395077 0.3385658  0.18600347 0.90335694 0.34156128 0.70788323]]
Random
[[0.76646433 0.81260938 0.5060734  0.76294637 0.91836396 0.88936564]
 [0.34935001 0.44619469 0.26535904 0.8210249  0.67885348 0.91165962]
 [0.32689913 0.09773757 0.91800077 0.82932094 0.81742948 0.29477066]]
arrange
[ 0 10 20 30 40 50 60 70 80 90]
Logic
[ True  True  True  True]
Sumation
450
minimum
[[0.4501989  0.81260938 0.5060734  0.46218705 0.74208781 0.46027288]
 [0.26662042 0.44619469 0.26535904 0.52986336 0.67885348 0.46117473]
 [0.18395077 0.09773757 0.18600347 0.82932094 0.34156128 0.29477066]]
maximum
[[0.76646433 0.89861108 0.64110013 0.76294637 0.91836396 0.88936564]
 [0.34935001 0.91817351 0.42469097 0.8210249  0.82111741 0.91165962]
 [0.32689913 0.3385658  0.91800077 0.9

In [ ]:
# Perform a logical "and":
np.logical_or(a, b)

### 5.3. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  

In [57]:
array_1 = [True, True, False, True, True, False]
array_2 = [False, False, True, True, False, False]

# Logic use of and
print(np.logical_and(array_1, array_2))

# Logic use of or
print(np.logical_or(array_1, array_2))

# Logic use of not
print(np.logical_not(array_1))

[False False False  True False False]
[ True  True  True  True  True False]
[False False  True False False  True]


## Expected Outcomes
At this point, you should feel comfortable with the following:
 - What is a NumPy array
 - Using NumPy array attributes 
 - Performing broadcasting
 - Using aggregate functions


## What to Turn in?
Be sure to **commit** and **push** your changes to this notebook.  All practice exercises should be completed.  Once completed, send a **Slack message** to the instructor indicating you have completed this assignment. The instructor will verify all work is completed. 